# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-27 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160626_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 6, 27, 15, 30, 59, 891664, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
