# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-01 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('posts', '0007_post_read_time'),
        ('comments', '0003_auto_20160629_0944'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
